
sudo: required
language: java

jdk:
  - oraclejdk7



script:
  - mvn clean cobertura:cobertura -Dtest=DefaultDockerClientTest#testExecInspect -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/docker-client/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "lSJrTUl2KBGIcO+Zp/HveOBGWETDS9h12UCGrzq+Z/+Q4RVUEdpx1zAlksEW/tqjSXQp2v+iECGp5Jzn7OKYkVAXHp0RNg2/nocBHSrXtV+kFVUacMe/xbJrmxacZ2HKnyecjrJyt4A4VGUaMnRxUGaVEht81YmI9BPZXKdbcFzMECN/4GfSr0d6Vfij/rJWK+H6X19NfBGc/M87vUCfn17E21r/mUtolqo+DSoZOjt8dycFNh1lnTdHFyGua1rMr7QFRMOwBABLTJFUWFathg8wzBmjgmRMyXK8Oo+Cleg2i3E9qslHtT5WP1aq0nBP4AQ7bByVtpa9nupExwbKXgbKqclRD0EkD8soH+iwjyBJRnAz1Jqx+dYUDoE+oSas9XU8EI6P7RmTPjWSxguU3mtSVQvQipkKoE2V0qH9NlwcFZjdU5vVQniyYBpBO24q+k35JorQRMTdXFcVlL2IyUhkwXqesEZkfg+RwAaaaSySrYXBNyJzM9GqHGzq5YeBPKX5MUdnCSUjKuaWichd09m5e1As4MLckgRzXgKvTLGnq4k5pFNAW3MA1sj1KBt2X8L07WaF5nLTRRa7tFPFwQ9gUgTr2IvCU6yRISKQ46OMyZCsm57B4v2X0evyneo/q4M5W18/J/HAPfm/AVSKbbyojPDGb47r6vKVmcls3ZI="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
